runtime:
  v_stack_leafs: True
  align_v_stack: True
  
window:
  name: "Tree visualization"
  width: 3840
  height: 2160
  background_color: [255, 255, 255]
  # background_color: [0, 0, 0]
layout:
  horizontal_spacing: 50
  vertical_spacing: 50

node:
  size:
    border_thickness: 5
    min_width: 200
    padding_x: 20
    padding_y: 10
  colors:
    text_color: [0, 0, 0]
    # text_color: [255, 255, 255]

    # Green
    # levels: [
    #   [20, 90, 20],
    #   [30, 125, 40],
    #   [60, 160, 70],
    #   [120, 195, 110],
    #   [180, 225, 170],
    # ]

    # Red
    levels: [
        [90, 20, 20],
        [125, 40, 40],
        [160, 70, 70],
        [195, 110, 110],
        [225, 170, 170],
    ]

    # Blue
    # levels: [
    #   [20, 20, 90],
    #   [40, 40, 125],
    #   [70, 70, 160],
    #   [110, 110, 195],
    #   [170, 170, 225],
    # ]

    # Yellow
    # levels: [
    #   [200, 200, 20],
    #   [220, 220, 40],
    #   [240, 240, 70],
    #   [250, 250, 110],
    #   [255, 255, 170],
    # ]

    # Purple
    # levels: [
    #   [90, 20, 90],
    #   [125, 40, 125],
    #   [160, 70, 160],
    #   [195, 110, 195],
    #   [225, 170, 225],
    # ]
  font:
    name: "Arial"
    size: 30