runtime:
  v_stack_leafs: True
  align_v_stack: True

window:
  name: "Tree visualization"
  width: 5020
  height: 2780
  scroll_speed_horizontal: 200
  scroll_speed_vertical: 100

node_size:
    min_width: 50
    border_thickness: 5
    margin_x: 20
    margin_y: 10

font:
  size: 40
  name: "Arial"

layout:
  horizontal_spacing: 50
  vertical_spacing: 50

colors:
  white: [255, 255, 255]
  gray: [175, 175, 175]
  black: [0, 0, 0]

color_palettes:
  green:
    - [30, 100, 30]
    - [70, 160, 70]
    - [140, 200, 140]

  red:
    - [100, 30, 30]
    - [180, 70, 70]
    - [230, 160, 160]

  blue:
    - [30, 30, 100]
    - [70, 70, 180]
    - [160, 160, 230]

  purple:
    - [90, 30, 90]
    - [160, 70, 160]
    - [225, 160, 225]
  
  teal:
    - [20, 90, 90]
    - [60, 160, 160]
    - [120, 210, 210]

  orange:
    - [180, 90, 30]
    - [220, 140, 60]
    - [240, 180, 120]

  brown:
    - [100, 50, 20]
    - [150, 90, 40]
    - [200, 140, 70]

  slate:
    - [50, 50, 70]
    - [90, 90, 120]
    - [140, 140, 170]