window:
  name: "Graph"
  width: 3840
  height: 2160
  background_color: [255, 255, 255]

layout:
  horizontal_spacing: 50
  vertical_spacing: 50

node:
  size:
    width: 400
    height: 160
    border_thickness: 5
    min_width: 200
    padding_x: 20
    padding_y: 10
  colors:
    levels: [
      [0, 53, 53],
      [0, 76, 76],
      [0, 162, 150],
      [211, 211, 211],
    ]
    background_color: [255, 255, 255]
  font:
    name: "Arial"
    size: 20